INSERT INTO productos (marca, costo_unitario, nombre) VALUES
("Dog Chow", 38.00, "Alimento Humedo Chicken Pouch Dog Chow X 100gr"),
("Dog Chow", 38.00, "Alimento Húmedo Pavo Pollo Pouch Dog Chow X 100g"),
("Dog Chow", 38.00, "Alimento Húmedo Pollo Dog Chow 100gr"),
("Dog Chow", 38.00, "Alimento Húmedo Pollo Dog Chow 100gr"),
("Dog Chow", 38.00, "Alimento Húmedo Puppy Chicken Dog Chow X 100gr"),
("Dog Chow", 38.00, "Alimento Húmedo Salmón Dog Chow 100gr"),
("Dog Chow", 38.00, "Alimento Húmedo Turkey Dinner Pouch Dog Chow 100gr"),
("Dog Chow", 1512.00, "Alimento Perro Adulto Dog Chow Bonus Bag 15+2kg"),
("Dog Chow", 377.00, "Alimento Perro Adultos +7 Dog Chow 3 Kg"),
("Dog Chow", 923.00, "Alimento Perro Adultos Medianos Y Grandes Dog Chow 8 Kg"),
("Dog Chow", 359.00, "Alimento Perro Adultos Minis Y Pequeños Dog Chow 3 Kg"),
("Dog Chow", 426.00, "Alimento Perro Control De Peso Dog Chow  3kg"),
("Dogui", 256.00, "Alimento Para Perro Cachorro Dogui 3kg"),
("Dogui", 239.00, "Alimento Para Perro Carne Asada Con Vegetales Dogui 3kg"),
("Dogui", 239.00, "Alimento Para Perro Carne Cereales Y Arroz Dogui 3 Kg"),
("Dr Zoo", 39.10, "Snacks Perro Dognuts Dr Zoo 50 Gr"),
("Generico", 105.00, "Snack Perro Trim Surtido 50 Gr"),
("Pedigree", 950.13, "Alimento Adulto +7 Carne Y Pollo Pedigree 7,5 Kg"),
("Pedigree", 99.86, "Alimento Adulto Carne Lata Pedigree 340 Gr"),
("Pedigree", 1454.37, "Alimento Adulto Carne Pollo Cereales Pedigree 15 Kg"),
("Pedigree", 1454.37, "Alimento Adulto Carne Y Vegetales Pedigree 15 Kg"),
("Pedigree", 852.46, "Alimento Adulto Carne Y Vegetales Pedigree 7,5 Kg"),
("Pedigree", 31.41, "Alimento Adulto Raza Peq Pollo Pedigree Pouch 100 Gr"),
("Pedigree", 31.41, "Alimento Cachorro Carne Pouch Pedigree 100 Gr"),
("Pedigree", 411.53, "Alimento Para Perro Cachorro Pedigree 3 Kg"),
("Pedigree", 395.64, "Alimento Para Perro Seco Vp Adulto Carne, Pollo Y Cereal Pedigree 3 Kg"),
("Pedigree", 411.53, "Alimento Para Perro Vp Adulto 7 Carne Y Pollo Pedigree 3kg"),
("Pedigree", 31.41, "Alimento Perro Razas Grandes Pollo Pedigree 100 Gr"),
("Pedigree", 411.53, "Alimento Seco Para Perro Verdura Y Pollo Adulto Rp Pedigree 3kg"),
("Pedigree", 31.79, "Snack Dentastix Razas Medianas Pedigree X 1un"),
("Pedigree", 26.58, "Snack Dentastix Razas Pequeñas Pedigree X 1un"),
("Pedigree", 133.42, "Snack Dentastix Razas Pequeñas Pedigree X 7un"),
("Pedigree", 79.71, "Snack Rodeo Carne Pedigree X 4un"),
("Pedigree", 79.71, "Snack Rodeo Pollo Pedigree X 4un"),
("Pet Class", 126.00, "Snack Para Perro Hueso 5/6 Pet Class 1un"),
("Raza", 228.00, "Alimento Perro Car Pol Cer Arr Raza 3kg"),
("Sabrositos", 1201.22, "Alimento Para Perro Carne Pollo Y Cerdo Sabrositos 20kg + 2kg"),
("Sabrositos", 939.02, "Alimento Para Perro Mix Carne Pollo Cerdo Sabrositos 15 + 1kg"),
("Sabrositos", 564.83, "Alimento Para Perro Mix Carne,Pollo Y Cerdo Sabrositos 8 Kg + 1kg"),
("Sabrositos", 945.74, "Alimento Para Perro Variedades Carne, Pollo, Arroz Y Vegetales Sabrositos 15kg"),
("Sabrositos", 277.77, "Alimento Perro Cachorro Sabrositos 3 Kg + 0,5 Kg"),
("Sabrositos", 702.75, "Alimento Perro Cachorro Sabrositos 8 Kg + 1 Kg"),
("Sabrositos", 240.89, "Alimento Perro Sabor Mix Sabrositos 3 Kg"),
("Tiernitos", 242.00, "Alimento Balanceado Perro Carne Tiernitos 3 Kg"),
("Tiernitos", 952.00, "Alimento Perro Carne Tiernitos 15 Kg"),
("Vaquero", 106.00, "Orejas Vacunas Vaquero 3 Un"),
("Voraz", 132.00, "Alimento Perros Balanceado Mix Carne Pollo Vegetales Voraz 2.7kg"),
("Voraz", 132.00, "Alimento Perros Balanceado Pollo Y Arroz Voraz 2.7 Kg");
